#!/usr/bin/env bash

# Set prefix for configure
CONFIGURE+=("--prefix=${HOME}/.local")

CFLAGS+=("-O3" "-DNDEBUG" "-pipe")
if [[ $(uname -s) == CYGWIN* ]]; then
    LDFLAGS+=("-Wl,--no-undefined")
fi

