#!/usr/bin/env bash
#*===========================================================================*
#*                                                                           *
#*  build - shell script for integration with vim                            *
#*                                                                           *
#*  Copyright (c) 2019 Frederic Jardon  <frederic.jardon@gmail.com>          *
#*                                                                           *
#*  ------------------ GPL Licensed Source Code ------------------           *
#*  Frederic Jardon makes this software available under the GNU              *
#*  General Public License (GPL) license for open source projects.           *
#*  For details of the GPL license please see www.gnu.org or read            *
#*  the file license.gpl provided in this package.                           *
#*                                                                           *
#*  This program is free software; you can redistribute it and/or            *
#*  modify it under the terms of the GNU General Public License as           *
#*  published by the Free Software Foundation; either version 3 of           *
#*  the License, or (at your option) any later version.                      *
#*                                                                           *
#*  This program is distributed in the hope that it will be useful,          *
#*  but WITHOUT ANY WARRANTY; without even the implied warranty of           *
#*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
#*  GNU General Public License for more details.                             *
#*                                                                           *
#*  You should have received a copy of the GNU General Public                *
#*  License along with this program in the file 'license.gpl'; if            *
#*  not, see <http://www.gnu.org/licenses/>.                                 *
#*  --------------------------------------------------------------           *
#*===========================================================================*

# Abort on any error
set -e

# Check if not called from inside VIM using project plugin
if [ -z "${GSL_PROJECT}" ]; then
    GSL_PROJECT=$(cd $(dirname $(dirname "$0")) ; pwd -P)
fi

# Configuration variables
BUILD_DIR="${GSL_PROJECT}-build"

# Handle option if any
if [ "$1" == "destroy" ]; then
    echo "Removing old build directory ..."
    rm -rf "${BUILD_DIR}"
    exit 0
fi

# Create the build directory
mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"

# Initial configuration of sources if needed
if [ ! -e "${BUILD_DIR}/config.status" ]; then
    echo "Configuring ..."
    "${GSL_PROJECT}/configure" --prefix="${HOME}/.local"
fi

ARGNO=0
if [ -n "$1" ]; then
    MAKE[${ARGNO}]="$1"
    ARGNO=$(expr ${ARGNO} + 1)
else
    MAKE[${ARGNO}]="all"
    ARGNO=$(expr ${ARGNO} + 1)
fi

MAKE[${ARGNO}]='CFLAGS=-g -O0 -Wall'
ARGNO=$(expr ${ARGNO} + 1)

# Platform specific tweaks
if [[ $(uname -s) == CYGWIN* ]]; then
    MAKE[${ARGNO}]="LDFLAGS=${LDFLAGS}${LDFLAGS+ }-no-undefined"
    ARGNO=$(expr ${ARGNO} + 1)
fi

# Make
if [[ "check" == "$1" ]]; then
    trap 'cat "${BUILD_DIR}/test-suite.log"' ERR
fi
make "${MAKE[@]}"


